### ISSUE TITLE
Error when running the script! Please checking the file (decrypted or not) or path to the file is correct!

### ISSUE THREAD

**Issue by NguyenHai79** [34306/unitydump-iOS#1]
- File global-metadata.dat đã được decrypted bằng IGG, tuy nhiên vẫn báo lỗi.
- Biểu tượng Filza ở gốc trên ko có phản hồi khi nhấn vào.
- Đã cài đặt qua TrollStore và esign vẫn bị lỗi.

12pm XinaA15.
Bạn có thể fix lỗi đc ko?

========
- File global-metadata.dat has been decrypted by IGG, but still gives error.
- The Filza icon at the top is unresponsive when tapped.
- Installed via TrollStore and esign still fails.

12pm XinaA15.
Can you fix the error?

**Comment by 34306** [comment]
XinaA15 have an issue where we can't fixed:
- Get folder created
- Get permisson for execute to run
Due to those issue, we decided to drop XinaA15 support even I'm using XinaA15.
